site_name: passport
site_description: ...
repo_url: https://github.com/asad-ishtiaque/codename_passport
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/asad-ishtiaque">asad-ishtiaque</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
