# Generated by Django 5.1.15 on 2026-07-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_inspection_certificate', '0002_rename_user_id_vehicleinspectioncertificate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspectioncertificate',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('EXTRACTED', 'Extracted'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicleinspectioncertificate',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspectioncertificate',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspectioncertificate',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspectioncertificate',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspectioncertificate',
            name='issue_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspectioncertificate',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspectioncertificate',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspectioncertificate',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
