# Generated by Django 5.1.15 on 2026-07-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving_license', '0004_drivinglicense_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivinglicense',
            name='image',
        ),
    ]
