# Generated by Django 5.1.15 on 2026-06-08 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence_permit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residencepermit',
            old_name='user_id',
            new_name='user',
        ),
    ]
