# Generated by Django 5.1.15 on 2026-07-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence_permit', '0002_rename_user_id_residencepermit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencepermit',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Unspecified')], max_length=1),
        ),
    ]
