# Generated by Django 5.1.15 on 2026-07-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence_permit', '0003_alter_residencepermit_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencepermit',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('EXTRACTED', 'Extracted'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20),
        ),
        migrations.AlterField(
            model_name='residencepermit',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residencepermit',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residencepermit',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='residencepermit',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Unspecified')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='residencepermit',
            name='issue_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='residencepermit',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residencepermit',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='residencepermit',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='residencepermit',
            name='permit_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
